package com.neosoft.phone.model;
// Generated 12 May, 2020 9:57:41 PM by Hibernate Tools 5.3.0.Beta2

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.neosoft.phone.enumModel.PhoneType;

/**
 * Phone generated by hbm2java
 */
@Entity
@Table
public class Phone implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	
	@Enumerated(EnumType.STRING)
    private PhoneType numberType;
	
	private Long number;
	private Integer customerid;

	public Phone() {
	}

	public Phone(PhoneType numberType, Long number, Integer customerid) {
		this.numberType = numberType;
		this.number = number;
		this.customerid = customerid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public PhoneType getNumberType() {
		return this.numberType;
	}

	public void setNumberType(PhoneType numberType) {
		this.numberType = numberType;
	}

	public Long getNumber() {
		return this.number;
	}

	public void setNumber(Long number) {
		this.number = number;
	}

	public Integer getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(Integer customerid) {
		this.customerid = customerid;
	}

}
